version: '3'

services:
  phpapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: phpapp:123
    ports: 
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    container_name: myphpapp-app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my!!!root!!!pw
    container_name: myphpapp-db
    command: --default-authentication-plugin=mysql_native_password

